project_id = "jpedvgjclutbyuljoxog"

[functions.generate-design]
verify_jwt = false

[functions.create-shazam3-agent]
verify_jwt = false

[functions.pipeline-spatial-analysis]
verify_jwt = false

[functions.blink-design]
verify_jwt = false

[functions.nano-planta]
verify_jwt = false

[functions.nano-elevacion]
verify_jwt = false

[functions.pipeline-items-extraction]
verify_jwt = false

[functions.pipeline-moodboard]
verify_jwt = false

[functions.pipeline-flatlay]
verify_jwt = false

[functions.pipeline-colors-textures]
verify_jwt = false

[functions.pipeline-storybook]
verify_jwt = false

[functions.pipeline-video-presentation]
verify_jwt = false
